language: csharp
mono: none
dotnet: 2.1.105
script:
- dotnet restore
- dotnet build --configuration Release
before_deploy:
- tar -zcf ${TRAVIS_BUILD_DIR}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz bin/Release/netcoreapp2.0
deploy:
  provider: releases
  api_key:
    secure: nLZsK9M7zioQUR498Qzai7J3bCimj3hp2XyFvttfYPSQdZKRj4ZwnOuSw1B6n8oaY9FeFZAqrHJTN8PqsBRPZPzYlw93EJ3J4wFy1x484fZ93NOtj785JlTK8SCbiuNC2nuZI70VYwk2ZZU3pXfpqM/7dnV0tngOreZDsyXnRClETpEA11kDnumPek8AD5DgdLP3TCpktCCZkiHGJxZwJNaSZYAj8Zyo4lsuhs6j62WHuKCIYVJMNU0zPm9wuCZApzqZbeIOapVvV2yYH8NrJpXIvBohQfR5ucv5EhEvYS7iUdzYuKUlyXdRV31A11EO77POntc/axHoI1uok9Csgl5Bcg5CYRutjnGa55DsRiNCVltfJKbezaxkG5AjLe3Ngtxch4/JrbbYNktOd024ofl1HbVe5j+qmbs59VrEKBUU8/8SscYEzBp4JF38LRvsNPPve1RW6F+pK8Nj/LZkHErwP+PRA5JH98FUwKdVibqX84FfQysH7YH4aRMOp74HaPEWFphChh9jr5TDy6/mT/FDQLEu0x7XsuRe43zBbFaxE82KVyeNEObZ9hdnM8jqh7Etm6RE5YUx8McRGJyv45peAFspXSR+HVUSGMvKs4b5wYo4O9l4WIhSsb9GM22OGSTUaINH/sAWwZMezEQOOVGxSnaViXPBBqLAJkgSK5E=
  file: ${TRAVIS_BUILD_DIR}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz
  skip_cleanup: true
  on:
    tags: true
